-- public.app definition

-- Drop table

-- DROP TABLE public.app;

CREATE TABLE public.app (
	id int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(80) NOT NULL,
	key varchar(250) NULL,
	CONSTRAINT pk_app PRIMARY KEY (id)
);


-- public.app_session definition

--

-- DROP TABLE public.app_session;

CREATE TABLE public.app_session (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"token" varchar(64) NOT NULL,
	app_id int2 NOT NULL,
	person_id int8 NULL,
	"type" varchar(1) NOT NULL,
	access_ip varchar(20) NULL,
	access_browser varchar(150) NULL,
	create_at timestamp NOT NULL,
	updated_at timestamp NOT NULL,
	CONSTRAINT app_session_pkey PRIMARY KEY (token)
);


-- public.configuration definition

-- Drop table

-- DROP TABLE public.configuration;

CREATE TABLE public.configuration (
	id varchar(80) NOT NULL,
	value text NOT NULL,
	description varchar NULL,
	CONSTRAINT configuration_un UNIQUE (id)
);

-- public.language definition

-- Drop table

-- DROP TABLE public.language;

CREATE TABLE public.language (
	id varchar(250) NOT NULL,
	region_country_id int4 NOT NULL,
	value varchar(250) NOT NULL,
	screen_id int4 NOT NULL
);


-- public.language_screen definition

-- Drop table

-- DROP TABLE public.language_screen;

CREATE TABLE public.language_screen (
	id int4 NOT NULL,
	description text NOT NULL,
	CONSTRAINT language_screen_pk PRIMARY KEY (id)
);


-- public.region_city definition

-- Drop table

-- DROP TABLE public.region_city;

CREATE TABLE public.region_city (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	state_id int4 NOT NULL,
	name varchar(250) NOT NULL,
	CONSTRAINT pk_region_city PRIMARY KEY (id)
);


-- public.region_country definition

-- Drop table

-- DROP TABLE public.region_country;

CREATE TABLE public.region_country (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(100) NOT NULL,
	code varchar(3) NOT NULL,
	initials varchar(3) NOT NULL,
	person_field_id int4 NULL,
	company_field_id int4 NULL,
	flag varchar(100) NULL,
	principal bool NOT NULL DEFAULT false,
	visible bool NOT NULL DEFAULT true,
	date_format varchar(50) NULL,
	date_hour_format varchar(50) NULL,
	locale varchar(50) NULL,
	timezone varchar(50) NULL,
	CONSTRAINT region_country_pkey PRIMARY KEY (id)
);


-- public.region_state definition

-- Drop table

-- DROP TABLE public.region_state;

CREATE TABLE public.region_state (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	country_id int2 NOT NULL,
	name varchar(100) NOT NULL,
	code varchar(15) NULL,
	initials varchar(15) NULL,
	CONSTRAINT pk_region_state PRIMARY KEY (id)
);